### ISSUE TITLE
security vulnerability in axios SNYK-JS-AXIOS-6032459

### ISSUE THREAD

**Issue by mishabruml** [DataDog/datadog-ci#1096]
### Bug description

https://security.snyk.io/vuln/SNYK-JS-AXIOS-6032459

Looks like it's not fixed at the moment in axios but I suppose it will be soon.

As an aside, the current version 0.21.4 used in this package is around 2 years old, is there any reason it couldn't be updated to the latest version 1.5.1? It would mean a major version change, there doesn't seem to be official breaking changes guide, there are some community ones though - see https://github.com/axios/axios/discussions/4996

### Command

None

**Comment by mishabruml** [comment]
looks like axios are on it https://github.com/axios/axios/issues/6022

**Comment by Drarig29** [comment]
Hi @mishabruml! We've had issues bumping axios in the past, because its move to ESM was not working properly with our standalone binary. Also, the latest fix that was published by axios seems to be a breaking change: https://github.com/axios/axios/pull/6028#issuecomment-1786789863

From the maintainer of axios:
> I felt that this was not an actual CVE in all honesty as the implementor has control over this and if they decide to set the flag to true they should have understood what that meant.

This is only a vulnerability when `withCredentials` is set to `true`, which isn't our case.

**Comment by tobiasweibel** [comment]
I can see the ESM issues and don't really like to fix such issues in projects of my company.
BUT: As my company runs security scanners it will assert the axios issue and we basically have to address it somehow.

**Comment by Drarig29** [comment]
Hi, just a heads up: we are working on it, a PR is being reviewed.

**Comment by mishabruml** [comment]
@Drarig29 thanks for this, could you re-open the issue until this is released? 😄

**Comment by Drarig29** [comment]
@mishabruml you can now use https://github.com/DataDog/datadog-ci/releases/tag/v2.23.1
