### ISSUE TITLE
Environment Variables Overrides Not Working

### ISSUE THREAD

**Issue by tomcrawf90** [DataDog/datadog-ci#174]
Hi, I'm looking for some validation to confirm if I'm doing something wrong or is something is not working with this tool. I'm attempting to trigger a synthetics test with a `simple.synthetics.json` file in my directory.

My file looks like this:
```json
{
  "tests": [
    {
      "id": "233-e2k-2hu",
      "config": {
        "startUrl": "https://{{HOST}}"
      }
    }
  ]
}
```

I have my dd keys and HOST variable set as follows:
```
export HOST="site.example.com"
```

Then when running the command everything works as expected, but the URL is not overwritten. 

However, if I use the following `simple.synthetics.json` file, this works:
```json
{
  "tests": [
    {
      "id": "233-e2k-2hu",
      "config": {
        "startUrl": "https://site.example.com"
      }
    }
  ]
}
```

I've also tried in the global settings in `datadog-ci.json` as follows and this is not working either:
```json
{
    "global": {
        "startUrl": "https://{{HOST}}"
    }
}
```

I've tried a number of variations of the environment variables available in the documentation including the `URL` variable and nothing seems to work, I always end up with the default start URL set on the Datadog site unless I override the startUrl without variables.

It would be great if someone could confirm if I'm doing something wrong, or if this functionality is broken?

Thanks

**Comment by m-rousse** [comment]
Hi @tomcrawf90,
The `startUrl` parameter is interpolated using the start URL configured for the test in Datadog. This is done by parsing the URL set in Datadog and overwriting the environment variables `URL`, `DOMAIN`, `HOST`, `HOSTNAME`, `ORIGIN`, `PARAMS`, `PATHNAME`, `PORT`, `PROTOCOL` and `SUBDOMAIN` with the corresponding part of the original start URL. 
This is done to allow for some URL rewriting by only replacing what is needed (eg. so that you could change the subdomain only to point to the staging one). As you pointed out, this list is available in the [documentation](https://docs.datadoghq.com/synthetics/ci/?tab=apitest#start-url).
For this reason even if you re-define an `HOST` environment variable, it will be overwritten by the one from the original start URL of the test. If you want to be able to set the host from an environment variable in your CI, you may do so using another name than those from the previous list.

**Comment by tomcrawf90** [comment]
Thanks, @m-rousse,

That explanation makes sense. So that takes me back to almost my first attempt at configuring this which is as follows:

`simple.synthetics.json`:
```json
{
  "tests": [
    {
      "id": "233-e2k-2hu",
      "config": {
        "startUrl": "{{SITE}}"
      }
    }
  ]
}
```

Then run with:
```shell
export SITE="https://site.example.com"
datadog-ci synthetics run-tests
```

This however hangs on the following output with no test initiated and nothing appearing in the DataDog console.
```
Finding files in /home/tom/tools/datadog-ci/{,!(node_modules)/**/}*.synthetics.json

Got test files:
  - simple.synthetics.json
```

Would you expect the above to work?

**Comment by m-rousse** [comment]
I would expect this to work, yes.
I tried to reproduce it on my end but did not manage to.
Which version of `datadog-ci` are you using? Could you ensure you are able to sed requests to both `https://intake.synthetics.datadoghq.com` and `https://api.datadoghq.com`?
