### ISSUE TITLE
Sourcemap - Optional release version

### ISSUE THREAD

**Issue by christoment** [DataDog/datadog-ci#176]
**Is your feature request related to a problem? Please describe:**
Looking at browser RUM configuration, the application version is not required (https://docs.datadoghq.com/real_user_monitoring/browser/). However, this is required in `datadog-cli` to upload sourcemaps.

**Describe the solution you'd like:**
Allow `datadog-cli` to upload sourcemaps with optional release-version argument.

**Describe alternatives you've considered:**
Placing the release version in the front-end but at this point it is an extra work that we want to avoid.

**Additional context:**
- N/A

**Comment by maximethedoggo** [comment]
Hello 👋,

Thanks for creating this issue!

The reason why we made the `release-version` a required argument is because from a version to another, the generated source maps can be very different. Without this release version, we do not think we can have a reliable enough unminification process (multiple versions of the app running at the same time, etc...). For now, we indeed suggest to our users to specify the version when initializing their RUM SDK 🙂

**Comment by christoment** [comment]
Hmmmmm that is a valid point!

But I wonder, could we make release version an optional but recommended argument for the command line?

The reason is that some framework like Angular automatically add hash into the bundle file name and it is enough for some team to version their production build with the hash in this case. 😃 

For workaround, we are currently considering to set a hardcoded version string just to have this source mapping feature, which is not ideal. :(

**Comment by maximethedoggo** [comment]
Hey @christoment, I agree this is not ideal 😬

I'll close this issue for now and reconsider later if we have additional users asking for this 👍

**Comment by ZeeCoder** [comment]
I'd second this.
I think newrelic takes the hash from the bundle itself so that I don't have to specify a version.
