### ISSUE TITLE
Unable to detect compiler

### ISSUE THREAD

**Issue by DocGreenRob** [DataDog/datadog-ci#714]
**Describe what happened**
I am not able to install the datadog-ci on my computer. 
Whenever I run below command I get an error
"`npm install --save-dev @datadog/datadog-ci`"

I get below error
"`Unable to detect compiler type`" on below file
node_modules\buildcheck\lib\index.js

**Expected behaviour:**
It should install the package.

**Actual behaviour:**
Not able to install package.

**Additional context**
 - OS version - Windows10
 - Node version - v14.17.6
 - an explanation of what might cause the bug and/or how it can be fixed

**Comment by DocGreenRob** [comment]
Wow, seriously, I take the biggest tool in the world, can't install it locally, create a bug and 5 days later no one says anything. Cool. All yall suck!

**Comment by DocGreenRob** [comment]
*trying to get sympathy...

**Comment by lefebvree** [comment]
Hello @DocGreenRob,

I did not manage to reproduce the issue on Windows 10 with Node v14.17.6, the package installs properly.

Can you post the installation logs with the error?

I think this is the same issue as reported in https://github.com/mscdex/cpu-features/issues/11.
Since buildcheck seems installed as a dependency of the optional cpu-features library, this may simply be a warning and the package installs successfully. Otherwise please try installing datadog-ci with the `--no-optional` flag:
```sh
npm install --no-optional --save-dev @datadog/datadog-ci
```

**Comment by DocGreenRob** [comment]
@lefebvree thanks very much for responding. Let me give this a try and follow back up.

**Comment by altmind** [comment]
Blocked by:

https://github.com/mscdex/ssh2/issues/1280
https://github.com/mscdex/cpu-features/issues/10
https://github.com/mscdex/buildcheck/issues/2
